from pathlib import Path


def test_useful_capacity_statute_is_non_negotiable() -> None:
    import json
    root = Path(__file__).parents[1]
    payload = json.loads(
        (root / "research/governance/persistent_research_acceleration_contract.json").read_text(encoding="utf-8")
    )
    rule = payload["useful_capacity_rule"]
    assert rule["status"] == "NON_NEGOTIABLE"
    assert "keine künstliche Arbeit" in rule["statement"]
    assert "wertvolle und hilfreiche Rechenarbeit" in rule["statement"]
    assert rule["no_padding"] is True
    assert rule["no_duplicate_work"] is True
    assert "completion-triggered replenishment" in rule["operational_rule"]


def test_completion_replenisher_is_event_driven_and_fail_closed() -> None:
    root = Path(__file__).parents[1]
    text = (root / ".github/workflows/continuous-useful-capacity-replenisher.yml").read_text(encoding="utf-8")
    assert "workflow_run:" in text
    assert "Permanent Windows Local Research Loop" in text
    assert "types: [completed]" in text
    assert "actions: write" in text
    assert "github.event.workflow_run.conclusion" in text
    assert "gh workflow run permanent-pc-research-loop.yml" in text
    assert "Scientific boundary unchanged" in text


def test_dashboard_never_maps_unavailable_runner_inventory_to_zero() -> None:
    root = Path(__file__).parents[1]
    text = (root / "automation/generate_resource_dashboard.py").read_text(encoding="utf-8")
    assert '"runner_api_visible": len(runners) if runners else None' in text
    generator = (root / "automation/generate_resource_dashboard.py").read_text(encoding="utf-8")
    script = (root / "docs/dashboard/dashboard.js").read_text(encoding="utf-8")
    assert '"runner_api_visible": len(runners) if runners else None' in generator
    assert '"capacity_state"' in generator
    assert '"unverified / not visible"' in generator
    assert 'capacity_state' in script


def test_dashboard_has_synchronous_bootstrap_and_bounded_refresh_fallback() -> None:
    root = Path(__file__).parents[1]
    html = (root / "docs/dashboard/index.html").read_text(encoding="utf-8")
    generator = (root / "automation/generate_resource_dashboard.py").read_text(encoding="utf-8")
    assert 'src="dashboard_bootstrap.js"' in html
    script = (root / "docs/dashboard/dashboard.js").read_text(encoding="utf-8")
    assert "renderEmbedded()" in script or "window.__TRADING_AGENT_SNAPSHOT__" in script
    assert "AbortController" in script
    assert "6000" in script
    assert "window.__TRADING_AGENT_SNAPSHOT__" in script
    assert 'BOOTSTRAP = ROOT / "docs" / "dashboard" / "dashboard_bootstrap.js"' in generator
    assert "window.__TRADING_AGENT_SNAPSHOT__" in generator


def test_dashboard_pages_has_single_automatic_publisher() -> None:
    root = Path(__file__).parents[1]
    text = (root / ".github/workflows/github-pages-dashboard.yml").read_text(encoding="utf-8")
    assert "workflow_dispatch: {}" in text
    assert '  push:\n    branches: [master]' not in text


def test_dashboard_update_persists_bootstrap() -> None:
    root = Path(__file__).parents[1]
    workflow = (root / ".github/workflows/resource-dashboard-update.yml").read_text(encoding="utf-8")
    assert "git diff --quiet -- docs/dashboard/dashboard_data.json docs/dashboard/dashboard_bootstrap.js" in workflow
    assert "git add docs/dashboard/dashboard_data.json docs/dashboard/dashboard_bootstrap.js" in workflow


def test_dashboard_bootstrap_ends_with_real_newline_not_literal_escape() -> None:
    root = Path(__file__).parents[1]
    bootstrap = (root / "docs/dashboard/dashboard_bootstrap.js").read_text(encoding="utf-8")
    assert bootstrap.endswith(";\n")
    assert not bootstrap.endswith(";\\n")
    assert bootstrap.splitlines()[0].startswith("// Generated by automation/generate_resource_dashboard.py")
