from pathlib import Path


def test_useful_capacity_statute_is_non_negotiable() -> None:
    import json
    root = Path(__file__).parents[1]
    payload = json.loads(
        (root / "research/governance/persistent_research_acceleration_contract.json").read_text(encoding="utf-8")
    )
    rule = payload["useful_capacity_rule"]
    assert rule["status"] == "NON_NEGOTIABLE"
    assert "keine künstliche Arbeit" in rule["statement"]
    assert "wertvolle und hilfreiche Rechenarbeit" in rule["statement"]
    assert rule["no_padding"] is True
    assert rule["no_duplicate_work"] is True
    assert "completion-triggered replenishment" in rule["operational_rule"]


def test_completion_replenisher_is_event_driven_and_fail_closed() -> None:
    root = Path(__file__).parents[1]
    text = (root / ".github/workflows/continuous-useful-capacity-replenisher.yml").read_text(encoding="utf-8")
    assert "workflow_run:" in text
    assert "Permanent Windows Local Research Loop" in text
    assert "types: [completed]" in text
    assert "actions: write" in text
    assert "github.event.workflow_run.conclusion" in text
    assert "gh workflow run permanent-pc-research-loop.yml" in text
    assert "Scientific boundary unchanged" in text


def test_dashboard_never_maps_unavailable_runner_inventory_to_zero() -> None:
    root = Path(__file__).parents[1]
    text = (root / "automation/generate_resource_dashboard.py").read_text(encoding="utf-8")
    assert '"runner_api_visible": len(runners) if runners else None' in text
    generator = (root / "automation/generate_resource_dashboard.py").read_text(encoding="utf-8")
    script = (root / "docs/dashboard/dashboard.js").read_text(encoding="utf-8")
    assert '"runner_api_visible": len(runners) if runners else None' in generator
    assert '"capacity_state"' in generator
    assert '"unverified / not visible"' in generator
    assert 'capacity_state' in script


def test_dashboard_has_synchronous_bootstrap_and_bounded_refresh_fallback() -> None:
    root = Path(__file__).parents[1]
    html = (root / "docs/dashboard/index.html").read_text(encoding="utf-8")
    generator = (root / "automation/generate_resource_dashboard.py").read_text(encoding="utf-8")
    assert 'src="dashboard_bootstrap.js"' in html
    script = (root / "docs/dashboard/dashboard.js").read_text(encoding="utf-8")
    assert "renderEmbedded()" in script or "window.__TRADING_AGENT_SNAPSHOT__" in script
    assert "AbortController" in script
    assert "6000" in script
    assert "window.__TRADING_AGENT_SNAPSHOT__" in script
    assert 'BOOTSTRAP = ROOT / "docs" / "dashboard" / "dashboard_bootstrap.js"' in generator
    assert "window.__TRADING_AGENT_SNAPSHOT__" in generator


def test_dashboard_pages_has_single_automatic_publisher() -> None:
    root = Path(__file__).parents[1]
    text = (root / ".github/workflows/github-pages-dashboard.yml").read_text(encoding="utf-8")
    assert "workflow_dispatch: {}" in text
    assert '  push:\n    branches: [master]' not in text


def test_dashboard_update_deploys_ephemeral_snapshot_without_master_commit_churn() -> None:
    root = Path(__file__).parents[1]
    workflow = (root / ".github/workflows/resource-dashboard-update.yml").read_text(encoding="utf-8")
    assert "upload-pages-artifact" in workflow
    assert "deploy-pages" in workflow
    assert "git push origin HEAD:master" not in workflow
    assert "git add docs/dashboard/dashboard_data.json" not in workflow


def test_dashboard_bootstrap_ends_with_real_newline_not_literal_escape() -> None:
    root = Path(__file__).parents[1]
    bootstrap = (root / "docs/dashboard/dashboard_bootstrap.js").read_text(encoding="utf-8")
    assert bootstrap.endswith(";\n")
    assert not bootstrap.endswith(";\\n")
    assert bootstrap.splitlines()[0].startswith("// Generated by automation/generate_resource_dashboard.py")


def test_dashboard_exposes_planned_capacity_as_non_authorizing_plan():
    root = Path(__file__).parents[1]
    generator = (root / "automation/generate_resource_dashboard.py").read_text(encoding="utf-8")
    script = (root / "docs/dashboard/dashboard.js").read_text(encoding="utf-8")
    html = (root / "docs/dashboard/index.html").read_text(encoding="utf-8")
    assert "planned_capacity_plan" in generator
    assert '"planned_capacity": planned_capacity' in generator
    assert '"planned_capacity_items"' in generator
    assert '"planned_capacity_note":' in generator
    assert 'data.planned_capacity||[]' in script
    assert "planned_not_started" in generator
    assert "Geplante Kapazität" in html
    assert "GEPLANT / NICHT GESTARTET" in script


def test_planned_capacity_planner_skips_active_duplicates_and_artificial_padding():
    from automation.generate_resource_dashboard import planned_capacity_plan
    resources = [
        {"name": "Windows self-hosted A", "capacity_state": "available", "current_assignments": 0},
        {"name": "Windows self-hosted B", "capacity_state": "operating", "current_assignments": 1},
        {"name": "Windows self-hosted C", "capacity_state": "unknown", "current_assignments": 0},
        {"name": "GitHub-hosted Ubuntu x64", "capacity_state": "available", "current_assignments": 0},
        {"name": "GitHub-hosted ARM64", "capacity_state": "available", "current_assignments": 0},
        {"name": "Free AI pool", "capacity_state": "available", "current_assignments": 0},
    ]
    work = [{"candidate": "Q218", "task": "Q218 work", "job": "Q218 PIT"}]
    top4 = [{"code": c, "next_gate": "gate"} for c in ("Q218", "Q219", "Q220", "Q221")]
    plan = planned_capacity_plan(resources, work, top4, {}, {}, {})
    by_resource = {x["resource"]: x for x in plan}
    planned_candidates = [
        x["planned_assignments"][0]["candidate"]
        for x in plan if x["planned_assignments"] and x["planned_assignments"][0].get("scheduled")
    ]
    assert all(
        item["candidate"] != "Q218" or item["plan_id"] == "Q218-ADVERSARIAL"
        for row in plan
        for item in row["planned_assignments"]
        if item.get("scheduled")
    )
    # Candidate duplication is forbidden only within the same execution lane;
    # a candidate may legitimately appear once for research and once for an
    # independent Free-AI review.
    scheduled_keys = [(item["candidate"], item.get("execution_workflow"), item.get("resource"))
                      for row in plan for item in row["planned_assignments"] if item.get("scheduled")]
    assert len(scheduled_keys) == len(set(scheduled_keys))
    assert by_resource["Free AI pool"]["planned_count"] == 1 or by_resource["Free AI pool"]["blocked_count"] == 0
    assert by_resource["Windows self-hosted B"]["planned_count"] == 0
    assert by_resource["Windows self-hosted C"]["blocked_count"] in (0, 1)
    assert all("planned_not_started" in item["planned_assignments"][0]["execution_status"] for item in plan if item["planned_assignments"] and item["planned_assignments"][0].get("scheduled"))



def test_dashboard_hides_operational_maintenance_from_active_jobs():
    root = Path(__file__).parents[1]
    generator = (root / "automation/generate_resource_dashboard.py").read_text(encoding="utf-8")
    for marker in (
        '"Resource Dashboard Update"',
        '"Current Operational Status Synchronizer"',
        '"Current Status Drift Guard"',
        '"Spine Next-Gate Autonomous Router"',
    ):
        assert marker in generator


def test_dashboard_exposes_live_berlin_clock():
    root = Path(__file__).parents[1]
    html = (root / "docs/dashboard/index.html").read_text(encoding="utf-8")
    script = (root / "docs/dashboard/dashboard.js").read_text(encoding="utf-8")
    assert 'id="clockTime"' in html
    assert 'id="clockDate"' in html
    assert 'Aktuelle Uhrzeit · Europe/Berlin' in html
    assert 'timeZone:"Europe/Berlin"' in script
    assert 'setInterval(updateClock,1000)' in script


def test_dashboard_research_note_excludes_platform_load():
    root = Path(__file__).parents[1]
    html = (root / "docs/dashboard/index.html").read_text(encoding="utf-8")
    generator = (root / "automation/generate_resource_dashboard.py").read_text(encoding="utf-8")
    assert "CI, Status-Synchronisierung und Pages" in html
    assert '"CI"' in generator and '"Full Suite Verification"' in generator

def test_dashboard_integrates_12h_milestone_history_into_snapshot():
    root = Path(__file__).parents[1]
    generator = (root / "automation/generate_resource_dashboard.py").read_text(encoding="utf-8")
    html = (root / "docs/dashboard/index.html").read_text(encoding="utf-8")
    script = (root / "docs/dashboard/dashboard.js").read_text(encoding="utf-8")
    assert "milestones_12h = milestone_history_12h()" in generator
    assert '"milestones_12h": len(milestones_12h)' in generator
    assert '"milestone_history_12h": milestones_12h' in generator
    assert 'id="milestones12h"' in html
    assert "data.milestone_history_12h||[]" in script


def test_dashboard_milestone_filter_excludes_platform_only_runs():
    from automation.generate_resource_dashboard import _is_research_milestone_run
    assert _is_research_milestone_run({"status": "completed", "conclusion": "success", "name": "Q220 As-Filed SEC-XBRL Population Repair"}) is True
    assert _is_research_milestone_run({"status": "completed", "conclusion": "success", "name": "Resource Dashboard Update"}) is False
    assert _is_research_milestone_run({"status": "completed", "conclusion": "success", "name": "CI"}) is False


def test_dashboard_exposes_six_job_future_queue():
    root = Path(__file__).parents[1]
    generator = (root / "automation/generate_resource_dashboard.py").read_text(encoding="utf-8")
    script = (root / "docs/dashboard/dashboard.js").read_text(encoding="utf-8")
    html = (root / "docs/dashboard/index.html").read_text(encoding="utf-8")
    assert "planned_research_backlog" in generator
    assert '"planned_research_queue_target": 6' in generator
    assert '"planned_research_queue_items"' in generator
    assert "planned_research_queue" in script
    assert 'id="plannedQueue"' in html


def test_dashboard_exposes_six_active_lane_target():
    root = Path(__file__).parents[1]
    generator = (root / "automation/generate_resource_dashboard.py").read_text(encoding="utf-8")
    script = (root / "docs/dashboard/dashboard.js").read_text(encoding="utf-8")
    html = (root / "docs/dashboard/index.html").read_text(encoding="utf-8")
    assert '"active_research_lanes_target": 6' in generator
    assert '"active_research_lanes_target_met"' in generator
    assert "active_research_lanes_target" in script
    assert 'id="laneTargetSummary"' in html


def test_dashboard_three_minute_live_refresh_and_five_minute_server_refresh():
    root = Path(__file__).parents[1]
    js = (root / "docs/dashboard/dashboard.js").read_text(encoding="utf-8")
    workflow = (root / ".github/workflows/resource-dashboard-update.yml").read_text(encoding="utf-8")
    assert "setInterval(load,180000)" in js
    assert 'cron: "*/5 * * * *"' in workflow


def test_dashboard_exposes_worker_purpose_target_and_eta_fields():
    root = Path(__file__).parents[1]
    generator = (root / "automation/generate_resource_dashboard.py").read_text(encoding="utf-8")
    script = (root / "docs/dashboard/dashboard.js").read_text(encoding="utf-8")
    html = (root / "docs/dashboard/index.html").read_text(encoding="utf-8")
    assert '"worker_status"' in generator
    assert '"purpose"' in generator
    assert '"target_worker"' in generator
    assert '"expected_start_at"' in generator
    assert '"expected_finish_at"' in generator
    assert '"open_pull_requests": prs' in generator
    assert 'id="workboardSummary"' in html
    assert 'id="prs"' in html
    assert 'Wer / Ressource' in script
    assert 'Nächster geplanter Start' in script
    assert 'data.open_pull_requests||[]' in script


def test_dashboard_open_prs_are_read_only_operational_metadata():
    root = Path(__file__).parents[1]
    generator = (root / "automation/generate_resource_dashboard.py").read_text(encoding="utf-8")
    script = (root / "docs/dashboard/dashboard.js").read_text(encoding="utf-8")
    assert "def open_pull_requests()" in generator
    assert '"/pulls?state=open&per_page=100&sort=updated&direction=desc"' in generator
    assert '"open_pull_requests": prs' in generator
    assert '"author"' in generator
    assert '"head_branch"' in generator
    assert '"base_branch"' in generator
    assert "prs.map" in script
