REQUEST_DASHBOARD_REFRESH=true
TRIGGER_DATE=2026-10-05
REASON=CHAT_AUTHORIZED_FINAL_CONTROL_BOARD_REFRESH
SOURCE=trading-agent-chat
PERFORMANCE=false
PROMOTION=false
LIVE_EXECUTION=false
TRIGGER_NONCE=DASHBOARD-CONTROL-BOARD-FINAL-R3
