REQUEST_DASHBOARD_REFRESH=true
TRIGGER_DATE=2026-10-05
REASON=CHAT_AUTHORIZED_REFRESH_AFTER_GENERATOR_REPAIR
SOURCE=trading-agent-chat
PERFORMANCE=false
PROMOTION=false
LIVE_EXECUTION=false
TRIGGER_NONCE=DASHBOARD-CONTROL-BOARD-REPAIR-R2
